name: business_banking
description: A demo app to showcase the clean framework for a business banking app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  clean_framework: ^0.4.1
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  url_launcher: ^6.0.3
  intl: ^0.17.0
  http: ^0.13.1
  card_scanner: ^0.2.2
#  integration_test: ^1.0.2+3
  charts_flutter: ^0.10.0
  permission_handler: ^5.1.0+2
  image_picker: ^0.7.4


  ### https://pub.dev/packages/pdf/versions/2.1.0
  pdf: ^2.1.0

  ### https://pub.dev/packages/printing/versions/4.1.0
  printing: ^4.1.0
  responsive_framework: 0.1.2
  flutter_svg: any

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  mockito: 4.1.4 # Apache 2.0
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login_hex_background.png
